name: CI

on:
  workflow_dispatch:

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print all context variables
        run: |
          echo "All context variables:"
          echo "${{ toJson(github) }}"
