name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'       # Specify the Java version you need
          distribution: 'adopt'    # You can use 'zulu', 'temurin', etc., depending on your preference

      - name: Compile Java application
        run: javac HelloWorld.java

      - name: Run Java application
        run: java HelloWorld
