name: CI Pipeline

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger builds on
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Specify the Java version you need

      - name: Compile Java application
        run: javac HelloWorld.java

      - name: Run Java application
        run: java HelloWorld
