name: GitHub Actions Maven Build Example

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2

      - name: Step 2 - List all files in the repository after checkout
        run: |
          ls -al

      - name: Step 3 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      - name: Step 4 - Build Maven Project
        run: |
          mvn -B package --file pom.xml

      - name: Step 5 - Run the Spring Boot Application
        run: |
          java -jar target/*.jar &  # Run the JAR file without specifying the full name
          sleep 10  # Wait for the application to start

      - name: Step 6 - List files in the root directory after build
        run: |
          ls -al

      - name: Step 7 - Check Application Status
        run: |
          curl -f http://localhost:8080 || exit 1  # Check if the application is accessible

      - name: Step 8 - Notify about the application URL
        run: |
          echo "The application is running at http://localhost:8080"
