name: Basic CI Workflow

on:
  push:
    branches:
      - main  # This triggers the workflow on push to the 'main' branch

jobs:
  print-info:
    runs-on: [self-hosted, venkat-server]  # This will run on your self-hosted runner named 'venkat-server'

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # This checks out the repository code

      - name: Print working directory and server name
        run: |
          echo "Current working directory:"
          pwd  # Prints the current directory where the job is running
          
          echo "Server name (hostname):"
          hostname  # Prints the hostname of the server where the job is running
