name: Clone and Modify

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  clone-modify-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB1_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.name "venkyy8"
          git config --global user.email "venkyy82@gmail.com"

      - name: Check if branch exists and switch/create
        run: |
          NEW_BRANCH="$(date +'%d%m%Y')"
          echo "Using branch: $NEW_BRANCH"

          git ls-remote --exit-code --heads origin "$NEW_BRANCH"
          if [ $? -eq 0 ]; then
            echo "Branch exists. Fetching and checking out."
            git fetch origin "$NEW_BRANCH"
            git checkout "$NEW_BRANCH"
          else
            echo "Branch does not exist. Creating it."
            git checkout -b "$NEW_BRANCH"
          fi

          echo "Modified on $(date)" >> file.txt
          git add file.txt
          git commit -m "Auto update on $(date +%d-%m-%Y)" || echo "Nothing to commit"

          # Set remote URL with token
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB1_TOKEN }}@github.com/venkyy8/GitHub-Actions

          git push origin "$NEW_BRANCH"
