name: CI

on:
  workflow_dispatch:

jobs:
  print-run-url:
    runs-on: ubuntu-latest
    steps:
      - name: Print run URL
        run: echo "This workflow run URL is: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
