name: CI

on:
  workflow_dispatch:

jobs:
  print-run-url:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow run URL
        run: |
          echo "This workflow run URL is: ${{ github.run_url }}"
