name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger builds on
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the target repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8' # Specify the Java version
          distribution: 'adopt' # Specify the JDK distribution

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests # No need to change directory

      - name: Build Docker image
        run: |
          docker build -t spring-boot-mongo-app . # Use current directory

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 spring-boot-mongo-app
