name: Clone and Modify

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  clone-modify-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # default token used here (safe)
