name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger builds on
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8' # Specify the Java version
          distribution: 'adopt' # Specify the JDK distribution

      - name: Build with Maven
        run: mvn clean package -DskipTests
<<<<<<< HEAD
        working-directory: spring-boot-mongo-docker # Use the path directly

      - name: Build Docker image
        run: docker build -t spring-boot-mongo-app .
        working-directory: spring-boot-mongo-docker # Use the path directly

      - name: Run Docker container
        run: docker run -d -p 8080:8080 spring-boot-mongo-app
        working-directory: spring-boot-mongo-docker # Use the path directly
=======
        working-directory: spring-boot-mongo-docker # Ensure it points to the correct directory

      - name: Build Docker image
        run: docker build -t spring-boot-mongo-app .
        working-directory: spring-boot-mongo-docker # Ensure it points to the correct directory

      - name: Run Docker container
        run: docker run -d -p 8080:8080 spring-boot-mongo-app
        working-directory: spring-boot-mongo-docker # Ensure it points to the correct directory
>>>>>>> 4114604a9fa9cd3cdff795974b8ebcb9035a6a14
