on:
  push:
    branches: [ main ]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2

      - name: Step 2 - List all files in the repository after checkout
        run: |
          ls -al

      - name: Step 3 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      - name: Step 4 - Build Maven Project
        run: |
          mvn -B package --file pom.xml

      - name: Step 5 - List files in the root directory after build
        run: |
          ls -al

      - name: Step 6 - Deploy to Nexus Repository
        env:
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          mvn -X deploy:deploy-file \
            -DgroupId=org.springframework.boot \
            -DartifactId=spring-boot-mongo \
            -Dversion=1.0 \
            -Dpackaging=jar \
            -Dfile=target/spring-boot-mongo-1.0.jar \
            -DrepositoryId=githubactions \
            -Durl=http://3.84.58.7:8081/repository/githubactions/ \
            -DgeneratePom=true

