name: Clone and Modify

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  clone-modify-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensures the token is used during checkout

      - name: Set up Git user
        run: |
          git config --global user.name "venkyy8"
          git config --global user.email "venkyy82@gmail.com"

      - name: Create branch, modify file, and push
        run: |
          NEW_BRANCH="$(date +'%d%m%Y')"
          echo "Creating branch: $NEW_BRANCH"
          git checkout -b "$NEW_BRANCH"

          echo "Modified on $(date)" >> file.txt
          git add file.txt
          git commit -m "Auto update on $(date +%d-%m-%Y)" || echo "Nothing to commit"

          # Set up authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git push origin "$NEW_BRANCH"
