name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger builds on
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the target repository
        uses: actions/checkout@v2
        with:
          repository: MithunTechnologiesDevOps/spring-boot-mongo-docker

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Change this to the version your application requires

      - name: Move to /opt
        run: |
          sudo mkdir -p /opt/spring-boot-mongo-docker
          sudo mv spring-boot-mongo-docker/* /opt/spring-boot-mongo-docker/
          sudo rm -rf spring-boot-mongo-docker # Clean up the old directory

      - name: Build with Maven
        run: |
          cd /opt/spring-boot-mongo-docker # Navigate to the new repo directory
          mvn clean install

      - name: Build Docker image
        run: |
          cd /opt/spring-boot-mongo-docker # Navigate to the new repo directory
          docker build -t spring-boot-mongo-app .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 spring-boot-mongo-app
