name: Clone and Modify

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  clone-modify-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # default token used here (safe)
        with:
          token: ${{ secrets.GITHUB1_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.name "venkyy8"
          git config --global user.email "venkyy82@gmail.com"

      - name: Check out existing branch or create new
        run: |
          NEW_BRANCH="$(date +'%d%m%Y')"
          echo "Using branch: $NEW_BRANCH"
          git fetch origin
          git checkout --track origin/$NEW_BRANCH 2>/dev/null || git checkout -b "$NEW_BRANCH"

      - name: Add and commit changes
        run: |
          echo "Modified on $(date)" >> file.txt
          git add file.txt
          git commit -m "Auto update on $(date +%d-%m-%Y)" || echo "Nothing to commit"

      - name: Push changes with PAT
        env:
          PAT: ${{ secrets.GITHUB1_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:$PAT@github.com/${{ github.repository }}
          git push origin "$(date +'%d%m%Y')"
