name: Build and Dockerize

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Update APT and install npm
        run: |
          sudo apt-get update
          sudo apt-get install npm -y

      - name: Install project dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Build Docker image
        run: docker build -t venkyy82/gh-actions:1.0 .

      - name: List Docker images
        run: docker images
