name: CI/CD

on:
  # Uncomment below if you want auto-deploy on main pushes
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Update APT and install npm
        run: |
          sudo apt-get update
          sudo apt-get install npm -y

      - name: Install project dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Run Trivy File System Scan (Non-blocking)
        run: trivy fs .

      - name: Build Docker image
        run: docker build -t venkyy82/gh-actions:${{ github.run_number }} .

      - name: Run Trivy Docker Image Scan (Non-blocking)
        run: trivy image venkyy82/gh-actions:${{ github.run_number }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push venkyy82/gh-actions:${{ github.run_number }}

      - name: Replace Docker image tag in deployment YAML
        run: |
          sed -i "s|image: venkyy82/gh-actions:.*|image: venkyy82/gh-actions:${{ github.run_number }}|g" deployment-service.yml

      - name: Upload modified YAML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-manifest
          path: deployment-service.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download deployment YAML artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-manifest
          path: .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name Demo --region ap-south-1

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment-service.yml

      - name: Wait for app to become ready
        run: |
          echo "Waiting 120 seconds for pods to start..."
          sleep 120

      - name: List Kubernetes Deployments
        run: kubectl get deployments

      - name: List Kubernetes Services
        run: kubectl get svc

      - name: List Kubernetes Pods
        run: kubectl get pods -o wide
